### ISSUE TITLE
Shortlist AI Generate Icon

### ISSUE THREAD

**Issue by Ken-Yeung** [Ken-Yeung/super-goggles#1]
# Objective

- [ ] Please help to generate some icons for the web application 
* Icon should relate to our web objective
* Need background `transparent version` and `normal version`

**Comment by Cywus98213** [comment]
What Color Scheme and theme  you want for the Logo? 
What is our store name?


i will make some prototype on the figma design, so you can make change or we can discuss the design for later on.

**Comment by Ken-Yeung** [comment]
This issue belongs to testing issue, please ignore this issue.
